version: '3.8'

services:
  sre-agent-api:
    build: ../python-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AWS_REGION=${AWS_REGION}
      - CLOUDWATCH_REGION=${CLOUDWATCH_REGION}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 4G
          cpus: '2'

  sre-agent-frontend:
    build: ..
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://your-alb-dns-name.us-east-1.elb.amazonaws.com:8000
    deploy:
      replicas: 2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 512M
